/* Body file for function TimeProvider
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "timeprovider.h"
#include <Hal.h>

static asn1SccTIME_PROVIDER_TIME reference_time = 0;
static asn1SccTIME_PROVIDER_TIME applied_reference_time = 0;

void timeprovider_startup(void)
{
}

void timeprovider_PI_init(void)
{
}

void timeprovider_PI_get_current_elapsed_time(asn1SccTIME_PROVIDER_TIME *OUT_current_time)
{
	*OUT_current_time = Hal_GetElapsedTimeInNs() - applied_reference_time;
}


void timeprovider_PI_get_time_reference_status(asn1SccTIME_PROVIDER_TIME_REFERENCE_STATUS *OUT_status)
{
	*OUT_status = 0;
}


void timeprovider_PI_set_reference_time_for_synchronization( const asn1SccTIME_PROVIDER_TIME *IN_sync_time)
{
	reference_time = *IN_sync_time;
}


void timeprovider_PI_synchronize_time(void)
{
	applied_reference_time = reference_time;
}


