/* Body file for function testfunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testfunction.h"

#ifdef GENERIC_LINUX_TARGET
#include <stdio.h>
#endif

void testfunction_startup(void)
{
}

void testfunction_PI_trigger(void)
{
	testfunction_RI_init();
	asn1SccTIME_PROVIDER_TIME time;
	testfunction_RI_get_current_elapsed_time(&time);

	asn1SccTIME_PROVIDER_TIME reference_time = 500000000;
	testfunction_RI_set_reference_time_for_synchronization(&reference_time);
	testfunction_RI_synchronize_time();
	testfunction_RI_get_current_elapsed_time(&time);


	asn1SccTIME_PROVIDER_TIME_REFERENCE_STATUS status;
	testfunction_RI_get_time_reference_status(&status);

#ifdef GENERIC_LINUX_TARGET
// The intended test is on SAMV71, using TASTE RTEMS SAMV71 Runtime, where inspection is performed via GDB.
// This is a fallback for Linux

	printf("Reported time: %ld\n", time);
	printf("Reported status: %d\n", status);
	if (status != TIME_PROVIDER_TIME_REFERENCE_STATUS_synchronized)
	{
		printf("TEST FAIL: incorrect status\n");
		exit(EXIT_FAILURE);
	}
	if (time < 500000000 || time > 501000000)
	{
		printf("TEST FAIL: incorrect time\n");
		exit(EXIT_FAILURE);
	}
	printf("TEST PASS\n");
	exit(EXIT_FAILURE);
#endif

}


